services:
  gdmt-ms-identitymanagement-neg-dev-ccpl-1:
    image: plchavez98/gdmt-ms-identitymanagement-neg:dev-ccpl-1
    container_name: gdmt-ms-identitymanagement-neg-dev-ccpl-1
    environment:
      CONTEXT_PATH: /api/dev-ccpl-1
      MS_VERSION: dev-ccpl-1
      PROFILE_ACTIVE: develop
      CONFIG_SERVER_URI: http://gdmt-ms-config-server:8888
      VAULT_SCHEME: http
      VAULT_HOST: gdmt-ms-vault-server
      VAULT_PORT: 8200
      VAULT_AUTHENTICATION: TOKEN
      VAULT_TOKEN: ${VAULT_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/dev-ccpl-1/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - gdmt-microservices-network
networks:
  gdmt-microservices-network:
    external: true