services:
  gdmt-ms-retentionschedules-neg-dev-ccpl-47:
    image: plchavez98/gdmt-ms-retentionschedules-neg:dev-ccpl-47
    container_name: gdmt-ms-retentionschedules-neg-dev-ccpl-47
    environment:
      CONTEXT_PATH: /api/dev-ccpl-47
      MS_VERSION: dev-ccpl-47
      PROFILE_ACTIVE: develop
      CONFIG_SERVER_URI: http://gdmt-ms-config-server:8888
      VAULT_SCHEME: http
      VAULT_HOST: gdmt-ms-vault-server
      VAULT_PORT: 8200
      VAULT_AUTHENTICATION: TOKEN
      VAULT_TOKEN: ${VAULT_TOKEN}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/dev-ccpl-47/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - gdmt-microservices-network
networks:
  gdmt-microservices-network:
    external: true