services:
  gdmt-ms-oauth2-server:
    image: plchavez98/gdmt-ms-oauth2-server:latest
    container_name: gdmt-ms-oauth2-server
    environment:
      CONTEXT_PATH: /api/develop
      MS_VERSION: develop
      PROFILE_ACTIVE: develop
      CONFIG_SERVER_URI: http://gdmt-ms-config-server:8888
      VAULT_SCHEME: http
      VAULT_HOST: gdmt-ms-vault-server
      VAULT_PORT: 8200
      VAULT_AUTHENTICATION: TOKEN
      VAULT_TOKEN: ${VAULT_TOKEN}
    restart: always
    networks:
      - gdmt-microservices-network
networks:
  gdmt-microservices-network:
    external: true