version: "3.8"
services:
# cross-cutting services start
  gdmt-ms-vault-server:
    image: plchavez98/vault-filesystem:0.2
    container_name: gdmt-ms-vault-server
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    volumes:
      - gdmt_vault_data:/vault/data
    restart: always
    networks:
      - gdmt-microservices-network
  gdmt-ms-postgres-server:
    image: postgres:12-alpine
    container_name: gdmt-ms-postgres-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - gdmt_postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - gdmt-microservices-network
  gdmt-ms-eureka-server:
    image: plchavez98/gdmt-ms-eureka-server:latest
    container_name: gdmt-ms-eureka-server
    ports:
      - "8761:8761"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gdmtmseurekaserver.rule=PathPrefix(`/eureka-server`)"
      - "traefik.http.services.gdmtmseurekaserver.loadbalancer.server.port=8761"
      - "traefik.http.middlewares.strip-eureka-prefix.stripprefix.prefixes=/eureka-server"
      - "traefik.http.routers.gdmtmseurekaserver.middlewares=strip-eureka-prefix"
      - "traefik.http.middlewares.rewrite-static.redirectregex.regex=^/eureka-server(.*)"
      - "traefik.http.middlewares.rewrite-static.redirectregex.replacement=/$1"
      - "traefik.http.middlewares.rewrite-static.redirectregex.permanent=false"
      - "traefik.http.routers.gdmtmseurekaserver.middlewares=strip-eureka-prefix,rewrite-static"
    networks:
      - gdmt-microservices-network
  gdmt-ms-config-server:
    image: plchavez98/gdmt-ms-config-server:latest
    container_name: gdmt-ms-config-server
    ports:
      - "8888:8888"
    environment:
      ENVIRONMENT: develop
      GIT_BRANCH: master
      GIT_USERNAMER: pedro-chavezcastro
      GIT_PASSWORD: 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
    restart: always
    networks:
      - gdmt-microservices-network
  gdmt-ms-oauth2-server:
    image: plchavez98/gdmt-ms-oauth2-server:latest
    container_name: gdmt-ms-oauth2-server
    environment:
      CONTEXT_PATH: /api/develop
      MS_VERSION: develop
      PROFILE_ACTIVE: develop
      CONFIG_SERVER_URI: http://gdmt-ms-config-server:8888
      VAULT_SCHEME: http
      VAULT_HOST: gdmt-ms-vault-server
      VAULT_PORT: 8200
      VAULT_AUTHENTICATION: TOKEN
      VAULT_TOKEN: ${VAULT_TOKEN}
    depends_on:
      - gdmt-ms-vault-server
      - gdmt-ms-postgres-server
      - gdmt-ms-eureka-server
      - gdmt-ms-config-server
    restart: always
    networks:
      - gdmt-microservices-network
# cross-cutting services end

# microservices start
        
  gdmt-ms-retentionschedules-neg-develop:
    image: plchavez98/gdmt-ms-retentionschedules-neg:develop
    container_name: gdmt-ms-retentionschedules-neg-develop
    environment:
      CONTEXT_PATH: /api/develop
      MS_VERSION: develop
      PROFILE_ACTIVE: develop
      CONFIG_SERVER_URI: http://gdmt-ms-config-server:8888
      VAULT_SCHEME: http
      VAULT_HOST: gdmt-ms-vault-server
      VAULT_PORT: 8200
      VAULT_AUTHENTICATION: TOKEN
      VAULT_TOKEN: ${VAULT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/develop/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - gdmt-ms-vault-server
      - gdmt-ms-postgres-server
      - gdmt-ms-eureka-server
      - gdmt-ms-config-server
    restart: always
    networks:
      - gdmt-microservices-network
                
  gdmt-ms-identitymanagement-neg-develop:
    image: plchavez98/gdmt-ms-identitymanagement-neg:develop
    container_name: gdmt-ms-identitymanagement-neg-develop
    environment:
      CONTEXT_PATH: /api/develop
      MS_VERSION: develop
      PROFILE_ACTIVE: develop
      CONFIG_SERVER_URI: http://gdmt-ms-config-server:8888
      VAULT_SCHEME: http
      VAULT_HOST: gdmt-ms-vault-server
      VAULT_PORT: 8200
      VAULT_AUTHENTICATION: TOKEN
      VAULT_TOKEN: ${VAULT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/develop/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - gdmt-ms-vault-server
      - gdmt-ms-postgres-server
      - gdmt-ms-eureka-server
      - gdmt-ms-config-server
    restart: always
    networks:
      - gdmt-microservices-network

# microservices end

# zuul server start 
  gdmt-ms-zuul-server:
    image: plchavez98/gdmt-ms-zuul-server:latest
    container_name: gdmt-ms-zuul-server
    ports:
      - "8090:8090"
    environment:
      CONFIG_SERVER_URI: http://gdmt-ms-config-server:8888
      PROFILE_ACTIVE: develop
    depends_on: 
      - gdmt-ms-eureka-server
      - gdmt-ms-config-server
      - gdmt-ms-oauth2-server
      # depends services start
                
      - gdmt-ms-retentionschedules-neg-develop
      - gdmt-ms-identitymanagement-neg-develop
      # depends services end
    restart: always
    networks:
      - gdmt-microservices-network
# zuul server end
volumes:
  gdmt_postgres_data:
  gdmt_vault_data:
networks:
  gdmt-microservices-network:
    external: true
