version: "3.8"
services:
# cross-cutting services start
  ms-postgres-server:
    image: postgres:12-alpine
    container_name: ms-postgres-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - gdmt_postgres_data:/var/lib/postgresql/data
    networks:
      - gdmt-microservices-network
  ms-eureka-server:
    image: plchavez98/ms-eureka-server:latest
    container_name: ms-eureka-server
    ports:
      - "8761:8761"
    networks:
      - gdmt-microservices-network
  ms-config-server:
    image: plchavez98/ms-config-server:latest
    container_name: ms-config-server
    ports:
      - "8888:8888"
    environment:
      ENVIRONMENT: develop
      GIT_BRANCH: master
      GIT_USERNAMER: pedro-chavezcastro
      GIT_PASSWORD: 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
    networks:
      - gdmt-microservices-network
  ms-oauth2-server:
    image: plchavez98/ms-oauth2-server:latest
    container_name: ms-oauth2-server
    environment:
      CONTEXT_PATH: /api/develop
      MS_VERSION: develop
      PROFILE_ACTIVE: develop
      CONFIG_SERVER_URI: http://ms-config-server:8888
      VAULT_SCHEME: http
      VAULT_HOST: vault_filesystem
      VAULT_PORT: 8200
      VAULT_AUTHENTICATION: TOKEN
      VAULT_TOKEN: ${VAULT_TOKEN}
    depends_on:
      - ms-postgres-server
      - ms-eureka-server
      - ms-config-server
    networks:
      - gdmt-microservices-network
# cross-cutting services end

# microservices start
        
  ms-identitymanagement-neg-develop:
    image: plchavez98/ms-identitymanagement-neg:develop
    container_name: ms-identitymanagement-neg-develop
    environment:
      CONTEXT_PATH: /api/develop
      MS_VERSION: develop
      PROFILE_ACTIVE: develop
      CONFIG_SERVER_URI: http://ms-config-server:8888
      VAULT_SCHEME: http
      VAULT_HOST: vault_filesystem
      VAULT_PORT: 8200
      VAULT_AUTHENTICATION: TOKEN
      VAULT_TOKEN: ${VAULT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/develop/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - ms-postgres-server
      - ms-eureka-server
      - ms-config-server
    networks:
      - gdmt-microservices-network
# microservices end

# zuul server start 
  ms-zuul-server:
    image: plchavez98/ms-zuul-server:latest
    container_name: ms-zuul-server
    ports:
      - "8090:8090"
    environment:
      CONFIG_SERVER_URI: http://ms-config-server:8888
      PROFILE_ACTIVE: develop
    depends_on: 
      - ms-eureka-server
      - ms-config-server
      - ms-oauth2-server
      # depends services start

      - ms-identitymanagement-neg-develop
      # depends services end
    networks:
      - gdmt-microservices-network
# zuul server end
volumes:
  gdmt_postgres_data:
networks:
  gdmt-microservices-network:
    external: true
